[package]
name = "mcp9808"
version = "0.1.0"
authors = ["lukwol <wolanczyk.lukasz@gmail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.2"
num-traits = { version = "0.2", default-features = false }
num-derive = "0.2"
i2c-reg = { version = "0.1", path = "../i2c-reg/i2c-reg" }
